# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://memorial.fctt.top/"
title: 纪念碑
languageCode: zh
DefaultContentLanguage: zh
theme: [ PaperMod ]

paginate: 9 # 每页显示的文章数

buildDrafts: false # 发布时包含草稿
buildFuture: false # 发布时包含未来日期的帖子
buildExpired: false # 发布时包含已过期的内容

enableInlineShortcodes: true # 允许内联短码
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
pygmentsUseClasses: true
mainsections: [] # 主页的列表内容
# googleAnalytics: UA-123-45 # 谷歌统计

minify:
  disableXML: true
  # minifyOutput: true

taxonomies: # 分类法配置
  tag: tags
  category: categories
  series: series
  authors: authors

outputs:
  home:
    - HTML
    - RSS
    - JSON

fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
    